2023-10-18 11:07:13,063 - ERROR - Exception Occured HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B24524F010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 11:07:13,067 - ERROR - No data available
2023-10-18 11:07:17,137 - ERROR - Exception Occured HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B245265190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 11:07:17,145 - ERROR - No data available
2023-10-18 11:07:21,235 - ERROR - Exception Occured HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B245267450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 11:07:21,235 - ERROR - No data available
2023-10-18 19:51:47,474 - ERROR - Exception occurred: HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024780E587D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 19:51:47,474 - ERROR - No data available
2023-10-18 19:51:52,542 - ERROR - Exception occurred: HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247831F8C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 19:51:52,542 - ERROR - No data available
2023-10-18 19:51:57,581 - ERROR - Exception occurred: HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247831FAED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 19:51:57,581 - ERROR - No data available
2023-10-18 19:52:02,640 - ERROR - Exception occurred: HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024783204E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 19:52:02,642 - ERROR - No data available
2023-10-18 19:52:07,697 - ERROR - Exception occurred: HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024783206E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 19:52:07,697 - ERROR - No data available
2023-10-18 19:56:38,851 - ERROR - Exception occurred: HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BD402587D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 19:56:38,851 - ERROR - No data available
2023-10-18 19:56:43,898 - ERROR - Exception occurred: HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BD42628C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 19:56:43,898 - ERROR - No data available
2023-10-18 19:56:48,952 - ERROR - Exception occurred: HTTPConnectionPool(host='localhost', port=4001): Max retries exceeded with url: /ltm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BD4262AED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-10-18 19:56:48,953 - ERROR - No data available
